{{--@extends('blade_rendering.main')--}}
@extends('example.public.main')

@push('head_scripts')
    {{-- Header StyleCSS Or JavaScripts--}}
@endpush

@section('content')
    <!-- MAIN CONTENT -->
    <section>
        <h1>About this hmvc page</h1>
        <p>The page you are viewing is dynamically generated by CodeIgniter using the BladeOne Blade Template Engine.</p>
        <p>If you want to prepare main content, you can find it at:</p>
        <pre><code>modules/Starter/Views/starter.blade.php</code></pre>
        <p>The controller for this page can be found at:</p>
        <pre><code>modules/Starter/Controllers/Starter.php</code></pre>
        <p>Routers for this page can be found at:</p>
        <pre><code>modules/Starter/Config/Routes.php</code></pre>
    </section>
@endsection

@push('foot_scripts')
    {{--  Page Level Footer Script --}}
    <script>
        function toggleMenu() {
            var menuItems = document.getElementsByClassName('menu-item');
            for (var i = 0; i < menuItems.length; i++) {
                var menuItem = menuItems[i];
                menuItem.classList.toggle("hidden");
            }
        }
    </script>
@endpush